### ISSUE TITLE
Error with ROS indigo on Jetson TK1

### ISSUE THREAD

**Issue by yukkysaito** [rt-net/rt_usb_9axisimu_driver#1]
Today, I tried to use this package with a rt_usb_9axis_imu.
However, this node put following the error message.
https://github.com/rt-net/rt_usb_9axisimu_driver/blob/master/src/rt_usb_9axisimu_driver.cpp#L223

I run this node with ROS indigo on Jetson TK1.
Jetson TK1 recognize the rt_usb_9axis_imu as /dev/ttyACM0.
Do you know anything?

先日、RTのIMUを購入し、本ノードの実行を試みたのですが、エラーで中断してしまいます。
下記のようなエラーメッセージが出るのですが、なにかご存知でしょうか？
https://github.com/rt-net/rt_usb_9axisimu_driver/blob/master/src/rt_usb_9axisimu_driver.cpp#L223

**Comment by yukkysaito** [comment]
Jetson TK1以外のデスクトップPC環境でも試してみましたが、同様でした。

**Comment by pazeshun** [comment]
Did you buy http://www.rt-shop.jp/index.php?main_page=product_info&cPath=1299_1309&products_id=3416 ?

**Comment by yukkysaito** [comment]
Yes, I bought it

**Comment by pazeshun** [comment]
Did you test Linux sample program of this IMU?

**Comment by pazeshun** [comment]
This issue may be caused by new firmware.
This repository works with previous version of IMU (http://www.rt-shop.jp/download/RT-IMU9/USB%E5%87%BA%E5%8A%9B9%E8%BB%B8IMU%E3%82%BB%E3%83%B3%E3%82%B5%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E4%BB%95%E6%A7%98%E6%9B%B8ver.1.2.pdf) for now.
The IMU now sold is new version described [here](https://github.com/rt-net/RT-USB-9AXIS-00).

Unfortunately, this repository doesn't work with new firmware even if you switch to binary output.
Please wait until fixing. Sorry.

**Comment by yukkysaito** [comment]
How can I confirm the version?

BTW, I tried to run with a Desktop PC, but same result.

> Unfortunately, this repository doesn't work with new firmware even if you switch to binary output.
> Please wait until fixing. Sorry.

Can you deal this issue?

**Comment by pazeshun** [comment]
This issue occurs in every environment for now.
I'll fix this issue.

**Comment by yukkysaito** [comment]
Thank you:) I'll be waitting

**Comment by pazeshun** [comment]
Sorry for waiting. I misunderstood. I don't have to fix source code in this repository.
Please see https://github.com/rt-net/rt_usb_9axisimu_driver/wiki#13-ver20%E3%81%A7%E3%81%AE%E3%81%94%E5%88%A9%E7%94%A8%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by pazeshun** [comment]
If you face any troubles about this, please tell me.

**Comment by yukkysaito** [comment]
Thank you!
But I cannot find the manual...
Please tell me how to change a mode.

**Comment by pazeshun** [comment]
Oh, sorry. Please see [manual branch](https://github.com/rt-net/RT-USB-9AXIS-00/tree/manual) for now.

**Comment by yukkysaito** [comment]
It worked on JetsonTk1 and others. Thank you so much.
