### ISSUE TITLE
Cannot install driver in Window 7 32 and 64 bits

### ISSUE THREAD

**Issue by minlattnwe** [rt-net/rt_usb_9axisimu_driver#3]
I cannot install the driver for the device in window 7 32 and 64 bits[
![window_7_64bit](https://cloud.githubusercontent.com/assets/28730868/26192531/ab082848-3be4-11e7-9fc1-461696601299.JPG)
](url)

**Comment by pazeshun** [comment]
Sorry for late response.
This repository is for ROS package, so you should move this issue to https://github.com/rt-net/RT-USB-9AXIS-00

**Comment by pazeshun** [comment]
Move to https://github.com/rt-net/RT-USB-9AXIS-00/issues/1

**Comment by rt-corp** [comment]
we moved this issue to https://github.com/rt-net/RT-USB-9AXIS-00/issues/1
