### ISSUE TITLE
Do you have a plan to release for noetic?

### ISSUE THREAD

**Issue by OTL** [rt-net/rt_usb_9axisimu_driver#39]
# 現状の問題点

rt_usb_9axisimu_driver is not released on Noetic yet. (I think it works)

# 改善案
Could you run bloom release for us?

**Comment by OTL** [comment]
FYI: The README says that there are noetic-devel branch, but it does not exist actually.

**Comment by ShotaAk** [comment]
We just preparing to release for Noetic.  (https://github.com/rt-net/rt_usb_9axisimu_driver/pull/37 , https://github.com/rt-net/rt_usb_9axisimu_driver/pull/38 )

Please wait for a moment.

**Comment by OTL** [comment]
Great! Arigatou gozaimasu!

**Comment by ShotaAk** [comment]
rosdistro ni PR dashimashita!
https://github.com/ros/rosdistro/pull/29572

**Comment by OTL** [comment]
Thanks a lot!!!
