### ISSUE TITLE
各共分散行列の対角成分の初期値について

### ISSUE THREAD

**Issue by TaiyouKomazawa** [rt-net/rt_usb_9axisimu_driver#41]
### 質問
　パラメータとして指定可能な３つの共分散行列の対角成分の平方根の初期値について、この定数はどのような根拠に基づき設定されたものですか。また、このパラメータが変更されるケースとしてどのようなことがありますか。

https://github.com/rt-net/rt_usb_9axisimu_driver/blob/ba6d56f7f80fed699a6d47480b88f675e589185d/include/rt_usb_9axisimu_driver/rt_usb_9axisimu.hpp#L130-L138

**Comment by ShotaAk** [comment]
これらの数値は実測値です。
センサモジュールの出力値をいくつかサンプリングし、その標準偏差をパラメータとして設定しています。

共分散行列を必要とするプログラムを作成する場合や、パッケージを使用する場合にパラメータを調整して下さい。

**Comment by TaiyouKomazawa** [comment]
なるほど。
静的パラメータであるということは、この共分散はノードの起動中において定数であるとしても問題ないと考えてよいですか。

**Comment by ShotaAk** [comment]
実際にはモジュールの姿勢や温度などによって共分散行列は動的に変化すると考えられます。
それらを考慮したノイズ計測を実施していないため、このパッケージでは共分散行列を定数値として設定しています。

**Comment by TaiyouKomazawa** [comment]
確かに、AHRSにKEFを用いるといった場合を除き、共分散行列を動的に設定する意味はあまりないようですね。
ご回答いただきありがとうございました。
