### ISSUE TITLE
キャリブレーションのやり方

### ISSUE THREAD

**Issue by fig-shimooka** [rt-net/rt_usb_9axisimu_driver#44]
キャリブレーションのやり方はどこかに記載されてますでしょうか？
紹介ページにもgithubにも載ってなかったので

**Comment by fig-shimooka** [comment]
失礼しました。
こちらに記載あることを見つけました
https://github.com/rt-net/RT-USB-9AXIS-00/blob/master/manual/USB%E5%87%BA%E5%8A%9B9%E8%BB%B8IMU%E3%82%BB%E3%83%B3%E3%82%B5ver2.0%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB.pdf

**Comment by ShotaAk** [comment]
解決して良かったです。

USB出力9軸IMUセンサver2.0マニュアル.pdf
の
4.6 センサキャリブレーションモードを参照してください。
