### ISSUE TITLE
ROS Noeticで2回目以降のノード起動でトピックメッセージが発行されない

### ISSUE THREAD

**Issue by hk-tst001** [rt-net/rt_usb_9axisimu_driver#56]
# 不具合の概要
ROS Noeticの環境でIMUのノードを起動する際、1回目は正常に/imu/data_rawのトピックメッセージが発行されますが、Ctrl+Cで停止後、再度IMUのノードを起動すると何もトピックメッセージが発行されなくなります。（このノードからの他のトピックメッセージも全て発行されません）
PCを再起動させるかIMUに接続されているUSBケーブルを抜き差しすることで、ノード起動後にトピックメッセージが正常に発行されるようになります。

# 実行環境
nVidia社のJetson AGX Orin
OS：Ubuntu 20.04、ROS Noetic
ソフトのバージョン：2024年7月17日時点の"noetic-devel"の最新バージョン

# 再現方法

1. ターミナルウィンドウ上で次のコマンドを実行する
    $ roslaunch rt_usb_9axisimu_driver rt_usb_9axisimu_driver.launch
3. 別のターミナルウィンドウ上で$ rostopic echo /imu/data_raw を実行し、トピックメッセージが発行されていることを確認
4. "Ctrl+C"でROSを停止する
5. 再度、1. のコマンドを実行する
6. 再度、3. でトピックメッセージを確認するが、発行されない（再現）

他に、Jetson NanoとJetson Xavier NXも所持しており両方ともROS Melodicで運用していますが、これらで同様の不具合は起こりません。

# 期待する動作
ROSを停止するたびにPCを再起動したりUSBケーブルの抜き差しをするのは現実的ではないので、毎回正常にトピックメッセージが発行されるようにしていただきたい。

# ログ・画像
* 不具合発生時の画面表示

```
$ roslaunch rt_usb_9axisimu_driver rt_usb_9axisimu_driver.launch 
... logging to /home/orin/.ros/log/2fbdadea-43fa-11ef-a349-48b02da4f002/roslaunch-orin-desktop-3496.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.198.194:37863/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /rt_usb_9axisimu_driver/frame_id: imu_link
 * /rt_usb_9axisimu_driver/port: /dev/9axisimu2

NODES
  /
    rt_usb_9axisimu_driver (rt_usb_9axisimu_driver/rt_usb_9axisimu_driver)

auto-starting new master
process[master]: started with pid [3504]
ROS_MASTER_URI=http://192.168.198.194:11311

setting /run_id to 2fbdadea-43fa-11ef-a349-48b02da4f002
process[rosout-1]: started with pid [3514]
started core service [/rosout]
process[rt_usb_9axisimu_driver-2]: started with pid [3517]
```
↑正常時はこの後に"Format check has completed."が続きますが、不具合発生時はここで止まります。

# その他
他にJetson NanoとJetson Xavier NXも所持しており、両方ともROS Melodicで運用していますが、これらで同様の不具合は起こりません。
正常動作時は"Ctrl+C"ですぐにコマンド入力できるようになりますが、不具合発生時は約15秒くらいかかってコマンド入力できるようになります。
添付ファイルは不具合発生時のログファイルです。
[roslaunch-orin-desktop-5939(NG).log](https://github.com/user-attachments/files/16260881/roslaunch-orin-desktop-5939.NG.log)

**Comment by ShotaAk** [comment]
DockerでROS Noetic環境を用意し動作確認しましたが、問題は再現しませんでした。

- Dockerベースイメージ：`ros:noetic`
- IMUパッケージ：aptでインストール（ros-noetic-rt-usb-9axisimu-driver）
- 実行コマンド：roslaunch rt_usb_9axisimu_driver rt_usb_9axisimu_driver.launch

---

IMU実機側との通信に不具合が起きているのか確認したいです。
下記のコマンドをROSノード起動前と、起動後（問題発生後）に実施し、データが出力されるか確認していただけますか？

```sh
# 出力結果は出力形式（バイナリ、ACII）によって異なります。
$ sudo stty -F /dev/ttyACM0 115200 raw
$ cat /dev/ttyACM0
194,0.004257,0.012771,0.001064,0.043945,-0.069824,0.955078,48.599998,6.000000,40.349998,41.397160
...
```

**Comment by hk-tst001** [comment]
ご確認いただきありがとうございます。
教えていただいた内容を確認しました。

- ROSノード起動前
　データが出力されます。ただし、いったんCtrl+Cで止めた後に再度catコマンドを実行すると出力されなくなりました。
- ROSノード起動後（問題発生後）
　データは出力されません。

接続先をMelodicの方に差し替えて同じ確認をしてみましたが、こちらは必ずデータが出力されます。

**Comment by ShotaAk** [comment]
ご確認ありがとうございます。

ROSを使わなくても問題が再現しているため、
ハードウェア（Jetson AGX Orin & Ubuntu 20.04）とIMU間の問題だと思われます。

次のコマンドで、usb周りのログを確認してもらえないでしょうか？

```sh
sudo dmesg | grep -i usb
```

正常時は下記のようなログが表示されます
```sh
# デバイスを接続したとき
[1271574.445082] usb 3-3.3: new full-speed USB device number 76 using xhci_hcd
[1271574.595245] usb 3-3.3: config 1 interface 1 altsetting 0 endpoint 0x3 has invalid maxpacket 128, setting to 64
[1271574.595267] usb 3-3.3: config 1 interface 1 altsetting 0 endpoint 0x83 has invalid maxpacket 128, setting to 64
[1271574.595943] usb 3-3.3: New USB device found, idVendor=2b72, idProduct=0003, bcdDevice= 1.00
[1271574.595952] usb 3-3.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1271574.595958] usb 3-3.3: Product: RT-USB-9AXIS-00
[1271574.595963] usb 3-3.3: Manufacturer: RT CORPORATION
[1271574.595968] usb 3-3.3: SerialNumber: 9AXIS-00
[1271574.609009] cdc_acm 3-3.3:1.0: ttyACM0: USB ACM device

# デバイスを外したとき
[1271635.348787] usb 3-3.3: USB disconnect, device number 76
````

**Comment by hk-tst001** [comment]
ありがとうございます。
ご指示いただいたコマンドを実行してみました。
以下のようになります。

# Ubuntu起動直後にデバイスを接続したとき
[  343.673808] usb 1-4.2: new full-speed USB device number 4 using tegra-xusb
[  343.781134] usb 1-4.2: config 1 interface 1 altsetting 0 endpoint 0x3 has invalid maxpacket 128, setting to 64
[  343.781475] usb 1-4.2: config 1 interface 1 altsetting 0 endpoint 0x83 has invalid maxpacket 128, setting to 64
[  343.785750] usb 1-4.2: New USB device found, idVendor=2b72, idProduct=0003, bcdDevice= 1.00
[  343.785804] usb 1-4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  343.785811] usb 1-4.2: Product: RT-USB-9AXIS-00
[  343.785817] usb 1-4.2: Manufacturer: RT CORPORATION
[  343.785820] usb 1-4.2: SerialNumber: 9AXIS-00
[  343.853799] cdc_acm 1-4.2:1.0: ttyACM0: USB ACM device
[  343.855354] usbcore: registered new interface driver cdc_acm
[  343.855358] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters


# デバイスを外したとき
[  438.493702] usb 1-4.2: USB disconnect, device number 4


# デバイスを接続したとき
[  489.564979] usb 1-4.2: new full-speed USB device number 5 using tegra-xusb
[  489.672389] usb 1-4.2: config 1 interface 1 altsetting 0 endpoint 0x3 has invalid maxpacket 128, setting to 64
[  489.672738] usb 1-4.2: config 1 interface 1 altsetting 0 endpoint 0x83 has invalid maxpacket 128, setting to 64
[  489.677017] usb 1-4.2: New USB device found, idVendor=2b72, idProduct=0003, bcdDevice= 1.00
[  489.677033] usb 1-4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  489.677038] usb 1-4.2: Product: RT-USB-9AXIS-00
[  489.677041] usb 1-4.2: Manufacturer: RT CORPORATION
[  489.677044] usb 1-4.2: SerialNumber: 9AXIS-00
[  489.684760] cdc_acm 1-4.2:1.0: ttyACM0: USB ACM device

**Comment by ShotaAk** [comment]
ご確認ありがとうございます。

不具合発生後のdmesg出力も見せていただけないでしょうか？
お手数をおかけします。

```sh
$ sudo stty -F /dev/ttyACM0 115200 raw
$ cat /dev/ttyACM0
Ctrl+Cで終了　（ここで、通信ができなくなる）

# ログ確認　（何らかのエラーメッセージが出ることを期待する）
$ sudo dmesg | grep -i usb

# grep無しでログ確認　（何かしらエラーが出ていないか確認する）
$ sudo dmesg
```

**Comment by hk-tst001** [comment]
ありがとうございます。
ご指示いただいたdmesgの出力結果を添付しました。
お手数おかけして申し訳ありませんが内容のご確認をお願いいたします。

- dmesg_all.txt：すべての確認をした後のdmesgのみの出力結果です。最初のIMUの接続で出力が無かったため、一度抜き差ししています。
状態のコメントを#####で記載していますのでご参考にしてください。
- dmesg_usb.txt："sudo dmesg | grep -i usb"の出力結果です。
[dmesg_all.txt](https://github.com/user-attachments/files/16278549/dmesg_all.txt)
[dmesg_usb.txt](https://github.com/user-attachments/files/16278551/dmesg_usb.txt)

**Comment by ShotaAk** [comment]
ログの提供ありがとうございます。
特にエラーメッセージは出力されてないですね。

このあとのステップとしては、NVIDIAのフォーラムで似たような問題が報告されていないかの調査になるので、
すぐに解決策を見つけるのは難しいです。

https://forums.developer.nvidia.com/

**Comment by hk-tst001** [comment]
いろいろとご対応いただきありがとうございます。
おかげでROSのバージョン違いが原因ではないこと、Jetson AGX Orin側に原因がありそうなことが分かりました。
これ以降は教えていただいたNVIDIAのフォーラム等を使用して調査したいと思います。
ありがとうございました。
